In [2]:
import numpy as np

In [3]:
self =np.array([1,2,3,4])
print(self)

[1 2 3 4]


In [7]:
B = np.zeros((3,3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
C = np.ones((4,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
D = np.empty((3,2))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
E = np.arange(12)
E

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
 E.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
F = np.linspace(2,10,5)
F

array([ 2.,  4.,  6.,  8., 10.])

In [38]:
G = np.arange(27).reshape(3,3,3)
G

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

    my_function()

In [4]:
def my_function():
    print("Hello World")
    my_function()